"""
Enumerations for the Alpha Research Trading System.

All enums are strongly typed to ensure consistency across the system.
These serve as the single source of truth for allowed values.
"""

from enum import Enum, auto
from typing import Set


class ActionType(str, Enum):
    """
    Allowed action types for proposals.

    Only Drift/Guard module can use DISABLE_MODULE and SET_MODULE_WEIGHT.
    All other modules are restricted to the first 6 actions.
    """
    NO_OP = "NO_OP"
    SCORE_PENALTY = "SCORE_PENALTY"
    SCORE_BONUS_SMALL = "SCORE_BONUS_SMALL"
    DELAY_TRADE = "DELAY_TRADE"
    REDUCE_POSITION_CAP = "REDUCE_POSITION_CAP"
    RAISE_UNCERTAINTY = "RAISE_UNCERTAINTY"
    DISABLE_MODULE = "DISABLE_MODULE"  # Only for Drift/Guard
    SET_MODULE_WEIGHT = "SET_MODULE_WEIGHT"  # Only for Drift/Guard

    @classmethod
    def standard_actions(cls) -> Set["ActionType"]:
        """Actions available to standard LLM modules (not Guard)."""
        return {
            cls.NO_OP,
            cls.SCORE_PENALTY,
            cls.SCORE_BONUS_SMALL,
            cls.DELAY_TRADE,
            cls.REDUCE_POSITION_CAP,
            cls.RAISE_UNCERTAINTY,
        }

    @classmethod
    def guard_only_actions(cls) -> Set["ActionType"]:
        """Actions only available to the Drift/Guard module."""
        return {cls.DISABLE_MODULE, cls.SET_MODULE_WEIGHT}


class EvidenceType(str, Enum):
    """Types of evidence that can be cited in proposals."""
    NEWS_ARTICLE = "NEWS_ARTICLE"
    SEC_FILING_CHUNK = "SEC_FILING_CHUNK"
    EARNINGS_CALL_CHUNK = "EARNINGS_CALL_CHUNK"
    INSIDER_FORM4_RECORD = "INSIDER_FORM4_RECORD"
    PRICE_SUMMARY = "PRICE_SUMMARY"
    MACRO_SNAPSHOT = "MACRO_SNAPSHOT"


class NewsFlag(str, Enum):
    """Flags for news/event classification."""
    # Earnings & Guidance
    EARNINGS_RELEASE = "EARNINGS_RELEASE"
    GUIDANCE_RAISE = "GUIDANCE_RAISE"
    GUIDANCE_CUT = "GUIDANCE_CUT"
    GUIDANCE_WITHDRAWN = "GUIDANCE_WITHDRAWN"
    REVENUE_WARNING = "REVENUE_WARNING"
    PROFIT_WARNING = "PROFIT_WARNING"

    # Capital Actions
    DIVIDEND_CHANGE = "DIVIDEND_CHANGE"
    BUYBACK_ANNOUNCEMENT = "BUYBACK_ANNOUNCEMENT"
    CAPITAL_RAISE = "CAPITAL_RAISE"
    DEBT_REFINANCE = "DEBT_REFINANCE"

    # Credit
    CREDIT_RATING_UP = "CREDIT_RATING_UP"
    CREDIT_RATING_DOWN = "CREDIT_RATING_DOWN"

    # M&A
    M_AND_A_RUMOR = "M_AND_A_RUMOR"
    M_AND_A_ANNOUNCED = "M_AND_A_ANNOUNCED"
    SPINOFF = "SPINOFF"

    # Regulatory & Legal
    REGULATORY_APPROVAL = "REGULATORY_APPROVAL"
    REGULATORY_RISK = "REGULATORY_RISK"
    SEC_PROBE = "SEC_PROBE"
    DOJ_PROBE = "DOJ_PROBE"
    LAWSUIT_FILED = "LAWSUIT_FILED"
    LAWSUIT_SETTLED = "LAWSUIT_SETTLED"
    ANTITRUST_RISK = "ANTITRUST_RISK"

    # Operations
    CYBERSECURITY_INCIDENT = "CYBERSECURITY_INCIDENT"
    DATA_BREACH = "DATA_BREACH"
    SUPPLY_CHAIN_DISRUPTION = "SUPPLY_CHAIN_DISRUPTION"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    PRODUCT_RECALL = "PRODUCT_RECALL"

    # Corporate
    MANAGEMENT_CHANGE = "MANAGEMENT_CHANGE"
    AUDITOR_CHANGE = "AUDITOR_CHANGE"
    ACCOUNTING_ISSUE = "ACCOUNTING_ISSUE"
    RESTATEMENT = "RESTATEMENT"
    BANKRUPTCY_RISK = "BANKRUPTCY_RISK"

    # Macro
    MACRO_SENSITIVE_EVENT = "MACRO_SENSITIVE_EVENT"
    GEOPOLITICAL_RISK = "GEOPOLITICAL_RISK"

    # Analyst
    ANALYST_UPGRADE = "ANALYST_UPGRADE"
    ANALYST_DOWNGRADE = "ANALYST_DOWNGRADE"


class FilingFlag(str, Enum):
    """Flags for SEC filing risk detection."""
    GOING_CONCERN = "GOING_CONCERN"
    LIQUIDITY_RISK = "LIQUIDITY_RISK"
    DEBT_COVENANT_RISK = "DEBT_COVENANT_RISK"
    MATERIAL_WEAKNESS_ICFR = "MATERIAL_WEAKNESS_ICFR"
    REVENUE_RECOGNITION_RISK = "REVENUE_RECOGNITION_RISK"
    ACCOUNTING_POLICY_CHANGE = "ACCOUNTING_POLICY_CHANGE"
    RESTATEMENT_RISK = "RESTATEMENT_RISK"
    OFF_BALANCE_SHEET_RISK = "OFF_BALANCE_SHEET_RISK"
    RELATED_PARTY_RISK = "RELATED_PARTY_RISK"
    CUSTOMER_CONCENTRATION_RISK = "CUSTOMER_CONCENTRATION_RISK"
    SUPPLIER_CONCENTRATION_RISK = "SUPPLIER_CONCENTRATION_RISK"
    LEGAL_CONTINGENCY_RISK = "LEGAL_CONTINGENCY_RISK"
    TAX_RISK = "TAX_RISK"
    FX_RISK = "FX_RISK"
    SEGMENT_WEAKNESS = "SEGMENT_WEAKNESS"
    MARGIN_COMPRESSION_RISK = "MARGIN_COMPRESSION_RISK"
    GUIDANCE_WITHDRAWN = "GUIDANCE_WITHDRAWN"
    AUDITOR_CHANGE = "AUDITOR_CHANGE"
    SHARE_DILUTION_RISK = "SHARE_DILUTION_RISK"
    CAPITAL_RAISE_RISK = "CAPITAL_RAISE_RISK"
    DEBT_MATURITY_WALL = "DEBT_MATURITY_WALL"
    IMPAIRMENT_RISK = "IMPAIRMENT_RISK"


class InsiderFlag(str, Enum):
    """Flags for insider trading pattern detection."""
    CLUSTER_BUY = "CLUSTER_BUY"
    CLUSTER_SELL = "CLUSTER_SELL"
    CEO_BUY = "CEO_BUY"
    CEO_SELL = "CEO_SELL"
    CFO_BUY = "CFO_BUY"
    CFO_SELL = "CFO_SELL"
    DIRECTOR_BUY = "DIRECTOR_BUY"
    DIRECTOR_SELL = "DIRECTOR_SELL"
    LARGE_TRADE = "LARGE_TRADE"
    UNUSUAL_ACTIVITY = "UNUSUAL_ACTIVITY"
    REPEATED_SELLING = "REPEATED_SELLING"
    PLAN_10B5_1 = "PLAN_10B5_1"
    OPTION_EXERCISE = "OPTION_EXERCISE"
    SALE_TO_COVER = "SALE_TO_COVER"
    GIFT_OR_TRANSFER = "GIFT_OR_TRANSFER"
    FIRST_TIME_BUY_IN_12M = "FIRST_TIME_BUY_IN_12M"


class IncidentSeverity(str, Enum):
    """Severity levels for operational incidents."""
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ErrorCode(str, Enum):
    """System error codes for unified error handling."""
    # Data layer errors
    E_DATA_SNAPSHOT_INCOMPLETE = "E_DATA_SNAPSHOT_INCOMPLETE"
    E_DATA_SOURCE_TIMEOUT = "E_DATA_SOURCE_TIMEOUT"
    E_LEDGER_WRITE_FAILED = "E_LEDGER_WRITE_FAILED"
    E_LEDGER_HASH_MISMATCH = "E_LEDGER_HASH_MISMATCH"
    E_POINT_IN_TIME_VIOLATION = "E_POINT_IN_TIME_VIOLATION"
    E_UNIVERSE_BUILD_FAILED = "E_UNIVERSE_BUILD_FAILED"
    E_MARKET_CALENDAR_UNKNOWN = "E_MARKET_CALENDAR_UNKNOWN"

    # LLM layer errors
    E_LLM_TIMEOUT = "E_LLM_TIMEOUT"
    E_LLM_SCHEMA_INVALID = "E_LLM_SCHEMA_INVALID"
    E_LLM_UNCITED_OUTPUT = "E_LLM_UNCITED_OUTPUT"
    E_LLM_BUDGET_EXCEEDED = "E_LLM_BUDGET_EXCEEDED"
    E_LLM_DRIFT_DETECTED = "E_LLM_DRIFT_DETECTED"

    # Portfolio layer errors
    E_PORTFOLIO_TURNOVER_BREACH = "E_PORTFOLIO_TURNOVER_BREACH"
    E_PORTFOLIO_CONSTRAINT_INFEASIBLE = "E_PORTFOLIO_CONSTRAINT_INFEASIBLE"
    E_PORTFOLIO_WEIGHT_NAN = "E_PORTFOLIO_WEIGHT_NAN"
    E_PORTFOLIO_UNSTABLE_OPTIMIZER = "E_PORTFOLIO_UNSTABLE_OPTIMIZER"

    # Risk layer errors
    E_RISK_DRAWDOWN_BREACH = "E_RISK_DRAWDOWN_BREACH"
    E_RISK_VAR_BREACH = "E_RISK_VAR_BREACH"
    E_RISK_CORR_BREACH = "E_RISK_CORR_BREACH"
    E_RISK_LIQUIDITY_BREACH = "E_RISK_LIQUIDITY_BREACH"
    E_RISK_KILL_SWITCH_TRIGGERED = "E_RISK_KILL_SWITCH_TRIGGERED"

    # Execution layer errors
    E_IBKR_CONNECT_FAILED = "E_IBKR_CONNECT_FAILED"
    E_ORDER_REJECTED = "E_ORDER_REJECTED"
    E_ORDER_DUPLICATE_BLOCKED = "E_ORDER_DUPLICATE_BLOCKED"
    E_FILL_MISMATCH = "E_FILL_MISMATCH"
    E_RECONCILE_MISMATCH = "E_RECONCILE_MISMATCH"

    # Operations errors
    E_MONITORING_DOWN = "E_MONITORING_DOWN"
    E_ALERT_DISPATCH_FAILED = "E_ALERT_DISPATCH_FAILED"


class ProposalRejectReason(str, Enum):
    """Reasons for rejecting a proposal from LLM or other modules."""
    SCHEMA_INVALID = "SCHEMA_INVALID"
    JSON_PARSE_ERROR = "JSON_PARSE_ERROR"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    EVIDENCE_IDS_EMPTY = "EVIDENCE_IDS_EMPTY"
    EVIDENCE_ID_NOT_FOUND_IN_LEDGER = "EVIDENCE_ID_NOT_FOUND_IN_LEDGER"
    EVIDENCE_LATE_AVAILABLE_AT = "EVIDENCE_LATE_AVAILABLE_AT"
    EVIDENCE_LATE_PUBLISHED_AT = "EVIDENCE_LATE_PUBLISHED_AT"
    EVIDENCE_HASH_MISMATCH = "EVIDENCE_HASH_MISMATCH"
    FORBIDDEN_ACTION = "FORBIDDEN_ACTION"
    SCORE_OUT_OF_RANGE = "SCORE_OUT_OF_RANGE"
    CONFIDENCE_OUT_OF_RANGE = "CONFIDENCE_OUT_OF_RANGE"
    FLAGS_OUT_OF_ENUM = "FLAGS_OUT_OF_ENUM"
    MODULE_NOT_ALLOWED = "MODULE_NOT_ALLOWED"
    BUDGET_EXCEEDED_GLOBAL = "BUDGET_EXCEEDED_GLOBAL"
    BUDGET_EXCEEDED_PER_SYMBOL = "BUDGET_EXCEEDED_PER_SYMBOL"
    DUPLICATE_PROPOSAL = "DUPLICATE_PROPOSAL"
    MODEL_DRIFT_GUARD_BLOCK = "MODEL_DRIFT_GUARD_BLOCK"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    TIMEOUT = "TIMEOUT"


class ModuleType(str, Enum):
    """Types of modules in the system."""
    LLM = "LLM"
    RULE = "RULE"
    FACTOR = "FACTOR"
    GATE = "GATE"


class RiskAction(str, Enum):
    """Actions taken by the risk gate."""
    APPROVE = "APPROVE"
    SCALE_RISK = "SCALE_RISK"
    SCALE_RISK_AND_NO_NEW = "SCALE_RISK_AND_NO_NEW"
    REDUCE_EXPOSURE = "REDUCE_EXPOSURE"
    KILL_SWITCH = "KILL_SWITCH"
    FREEZE_TRADING = "FREEZE_TRADING"


class OrderType(str, Enum):
    """Order types for execution."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    MOC = "MOC"  # Market on Close
    LOC = "LOC"  # Limit on Close


class OrderSide(str, Enum):
    """Order side."""
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    """Order status."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class SystemState(str, Enum):
    """Overall system state."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FROZEN = "FROZEN"
    KILLED = "KILLED"
